/* Hubs de clúster del blog (/guias/…): agrupan los artículos por tema y los conectan con la página
   comercial principal. Título y texto de cada tarjeta vienen del title y la description reales de
   cada página (no se reescriben a mano), así que no pueden contradecirlas. Regenerar si cambian. */
import type { PageData } from '../types';

const parent = { slug: 'guias', label: 'Guías' };

export const clusters: PageData[] = [
  {
    slug: 'guias',
    title: 'Guías para negocios en Panamá y Miami | Elemento Web',
    description: 'Guías por tema sobre diseño web, tiendas online, SEO, WhatsApp, IA y marketing para negocios en Panamá y Miami, ordenadas para encontrar lo que necesitas.',
    h1: 'Guías para tu negocio',
    breadcrumb: 'Guías',
    lead: ['Más de 70 guías ordenadas por tema. Elige el tuyo y sigue de lo general a lo específico.'],
    blocks: [
      {
        type: 'cards',
        h2: 'Temas',
        items: [
          { h3: 'Diseño web en Panamá', text: 'Todas las guías para decidir tu web en Panamá: cuánto cuesta cada tipo de sitio, cuánto tarda, cómo elegir agencia y plataforma, y qué errores evitar.', link: { slug: 'guias/diseno-web-panama', label: 'Ver las guías de diseño web en panamá' } },
          { h3: 'Tiendas online y pagos', text: 'Guías para crear y hacer crecer una tienda online en Panamá: cuánto cuesta, Yappy y otros métodos de pago, Shopify o WooCommerce y carritos abandonados.', link: { slug: 'guias/tiendas-online-y-pagos', label: 'Ver las guías de tiendas online y pagos' } },
          { h3: 'SEO y posicionamiento', text: 'Guías de SEO para negocios en Panamá: cómo aparecer en Google, elegir palabras clave, SEO local, Google Business Profile, velocidad y cómo medir resultados.', link: { slug: 'guias/seo-y-posicionamiento', label: 'Ver las guías de seo y posicionamiento' } },
          { h3: 'WhatsApp, IA y automatización', text: 'Guías para vender por WhatsApp, usar IA y automatizar el seguimiento de clientes en Panamá: chatbots, CRM, n8n, campañas y embudos de venta.', link: { slug: 'guias/whatsapp-ia-y-automatizacion', label: 'Ver las guías de whatsapp, ia y automatización' } },
          { h3: 'Marketing y pauta', text: 'Guías de marketing digital para negocios en Panamá: Google Ads o Facebook Ads, cuánto invertir en pauta, email marketing y contenido para redes.', link: { slug: 'guias/marketing-y-pauta', label: 'Ver las guías de marketing y pauta' } },
          { h3: 'Diseño web para Miami', text: 'Guías para negocios hispanos de Miami que quieren una web: cuánto cuesta, cómo elegir agencia y qué necesita el sitio. Servicio remoto desde Panamá.', link: { slug: 'guias/diseno-web-miami', label: 'Ver las guías de diseño web para miami' } },
          { h3: 'Diseño web por industria', text: 'Guías de diseño web para abogados, clínicas, restaurantes, hoteles, constructoras, contadores y más sectores en Panamá: qué necesita la web de cada uno.', link: { slug: 'guias/diseno-web-por-industria', label: 'Ver las guías de diseño web por industria' } },
        ],
      },
      { type: 'related', items: [{ slug: 'blog', label: 'Todo el blog' }, { slug: 'precios', label: 'Precios' }, { slug: 'casos-de-exito', label: 'Casos de éxito' }] },
      { type: 'form', h2: '¿No encuentras lo que buscas?', intro: 'Cuéntanos tu caso y te respondemos el mismo día hábil.' },
    ],
  },
  {
    slug: 'guias/diseno-web-panama',
    parent,
    title: 'Guías para planear tu web en Panamá: precios y decisiones',
    description: 'Todas las guías para decidir tu web en Panamá: cuánto cuesta cada tipo de sitio, cuánto tarda, cómo elegir agencia y plataforma, y qué errores evitar.',
    h1: 'Guías para planear y elegir tu web en Panamá',
    breadcrumb: 'Diseño web en Panamá',
    lead: ['Las guías que responden las preguntas de quien está por contratar una web: costo, plazos, plataforma, agencia y errores comunes. Empieza por la página principal y sigue por lo que necesites.'],
    blocks: [
      {
        type: 'cards',
        h2: 'Empieza aquí',
        intro: 'Las páginas principales del tema.',
        items: [
          { h3: 'Diseño Web en Panamá | Páginas que Consiguen Clientes', text: 'Diseño web en Panamá para empresas que quieren vender: sitios corporativos, tiendas online y landing pages. SEO, WhatsApp y precio cerrado desde $950.', link: { slug: 'diseno-web-panama', label: 'Ver la página' } },
          { h3: 'Precios de páginas web en Panamá: Landing, PYME y E-commerce', text: 'Precios de diseño web en Panamá: landing desde $550, sitio corporativo desde $950 y tienda online desde $1,500. Qué incluye cada uno, qué se paga aparte y cómo se paga.', link: { slug: 'precios', label: 'Ver la página' } },
          { h3: 'Diseño Web Corporativo en Panamá | Sitios que dan Confianza', text: 'Diseño web corporativo en Panamá para empresas que necesitan proyectar solidez: estructura clara, SEO por servicio y panel autoadministrable.', link: { slug: 'servicios/diseno-web-corporativo-panama', label: 'Ver la página' } },
          { h3: 'Landing Pages en Panamá | Alta Conversión desde $550', text: 'Landing pages de alta conversión en Panamá: una página, una oferta, una acción. El destino correcto para tu pauta. Entrega en 5 días hábiles.', link: { slug: 'servicios/landing-pages-alta-conversion-panama', label: 'Ver la página' } },
        ],
      },
      {
        type: 'cards',
        h2: 'Guías del tema',
        items: [
          { h3: '¿Cuánto cuesta una página web en Panamá? Guía de precios 2026', text: 'Rangos reales de precio para una página web en Panamá según el tipo de proyecto, qué encarece una web y por qué lo barato termina saliendo más caro.', link: { slug: 'blog/cuanto-cuesta-diseno-web-panama', label: 'Leer la guía' } },
          { h3: 'Cuánto cuesta una landing page en Panamá', text: 'Una landing page con Elemento Web cuesta $550 sin ITBMS. Qué incluye, qué se paga aparte y cuándo una landing no es lo que tu negocio necesita.', link: { slug: 'blog/cuanto-cuesta-una-landing-page-panama', label: 'Leer la guía' } },
          { h3: 'Cuánto cuesta rediseñar una página web', text: 'Un rediseño web parte del precio de un sitio nuevo (desde $950) más la auditoría y la migración. Qué lo define, qué va aparte y cuándo no rediseñar.', link: { slug: 'blog/cuanto-cuesta-redisenar-una-pagina-web', label: 'Leer la guía' } },
          { h3: 'Cuánto cuesta el desarrollo web a medida', text: 'El desarrollo web a medida parte desde $2,900 sin ITBMS. Qué mueve el costo, qué se cotiza aparte y cuándo un proyecto a medida no te conviene.', link: { slug: 'blog/cuanto-cuesta-desarrollo-web-a-medida-panama', label: 'Leer la guía' } },
          { h3: 'Cuánto cuesta el mantenimiento web en Panamá', text: 'El mantenimiento web parte desde $59 al mes, sin ITBMS. Qué cambia entre los planes, qué se paga aparte y cuándo no necesitas contratarlo.', link: { slug: 'blog/cuanto-cuesta-mantenimiento-web-panama', label: 'Leer la guía' } },
          { h3: '¿Cuánto tiempo toma hacer una página web? Plazos reales', text: 'Plazos reales de una página web en Panamá por tipo de proyecto, sus etapas y qué la retrasa de verdad: tu contenido.', link: { slug: 'blog/cuanto-tiempo-toma-hacer-una-pagina-web', label: 'Leer la guía' } },
          { h3: 'Cómo elegir una agencia de diseño web en Panamá', text: 'Señales de una buena agencia de diseño web en Panamá, qué preguntar antes de firmar y las banderas rojas que anuncian problemas.', link: { slug: 'blog/como-elegir-agencia-diseno-web-panama', label: 'Leer la guía' } },
          { h3: 'Landing page vs sitio web: cuál necesita tu negocio en Panamá', text: 'Landing page o sitio web: en qué se diferencian, cuándo conviene cada uno y cuánto cuestan en Panamá. Guía para elegir bien.', link: { slug: 'blog/landing-page-vs-sitio-web-cual-necesitas', label: 'Leer la guía' } },
          { h3: '¿Cuál es la mejor plataforma para crear una página web?', text: 'Comparamos Wix, Squarespace, WordPress y desarrollo a medida en Panamá: para qué sirve cada uno y cuándo un builder gratis se queda corto.', link: { slug: 'blog/mejor-plataforma-para-crear-una-pagina-web', label: 'Leer la guía' } },
          { h3: 'WordPress vs Shopify: cuál elegir para tu web en Panamá', text: 'WordPress vs Shopify en Panamá: cuándo conviene cada uno, costos reales, control y el factor local de Yappy y WhatsApp.', link: { slug: 'blog/diferencia-wordpress-shopify-diseno-web', label: 'Leer la guía' } },
          { h3: 'Por qué tu negocio en Panamá necesita una web en 2026', text: 'Las redes sociales no son tuyas y no bastan. Descubre por qué tu negocio en Panamá necesita una página web propia en 2026: confianza, Google y ventas 24/7.', link: { slug: 'blog/por-que-tu-negocio-necesita-una-pagina-web', label: 'Leer la guía' } },
          { h3: '7 errores de diseño web que le cuestan clientes a tu empresa', text: 'Los 7 errores de diseño web más comunes en las empresas panameñas —sin SEO, lentas, sin WhatsApp, sin móvil— y cómo corregirlos para dejar de perder clientes.', link: { slug: 'blog/errores-comunes-diseno-web-empresas', label: 'Leer la guía' } },
          { h3: 'Rediseño web: 8 señales de que tu sitio ya lo necesita', text: 'Ocho señales de que tu sitio necesita rediseño, qué conviene conservar y cómo rehacerlo sin perder tu posicionamiento.', link: { slug: 'blog/cuando-hacer-rediseno-pagina-web', label: 'Leer la guía' } },
          { h3: 'Tendencias de diseño web 2026 para negocios en Panamá', text: 'Las tendencias de diseño web 2026 que sí valen para tu negocio en Panamá: velocidad, IA con criterio, móvil primero y accesibilidad. Y cuáles ignorar sin culpa.', link: { slug: 'blog/tendencias-de-diseno-web-2026-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web responsive: primero el celular', text: 'Qué es el diseño web responsive y por qué en Panamá tu página debe pensarse primero para el celular. Errores típicos en móvil.', link: { slug: 'blog/diseno-web-responsive-mobile-first-panama', label: 'Leer la guía' } },
          { h3: 'Cómo elegir el dominio web perfecto para tu negocio', text: 'Guía práctica para elegir el dominio de tu negocio en Panamá: .com o .com.pa, nombre corto y memorable, a nombre de tu empresa y errores que debes evitar.', link: { slug: 'blog/como-elegir-el-dominio-web-perfecto', label: 'Leer la guía' } },
          { h3: 'Hosting en Panamá: por qué el hosting barato te sale caro', text: 'Un hosting barato ahorra unos dólares al mes y cuesta caídas, lentitud y sustos de seguridad. Qué mirar al elegir hosting para tu negocio en Panamá.', link: { slug: 'blog/hosting-panama-evitar-hosting-barato', label: 'Leer la guía' } },
        ],
      },
      { type: 'related', items: [{ slug: 'guias', label: 'Todas las guías' }, { slug: 'precios', label: 'Precios' }, { slug: 'casos-de-exito', label: 'Casos de éxito' }, { slug: 'contacto', label: 'Contacto' }] },
      { type: 'form', h2: '¿Quieres que lo veamos contigo?', intro: 'Cuéntanos tu caso y te respondemos el mismo día hábil.' },
    ],
  },
  {
    slug: 'guias/tiendas-online-y-pagos',
    parent,
    title: 'Guías de tiendas online y pagos en Panamá',
    description: 'Guías para crear y hacer crecer una tienda online en Panamá: cuánto cuesta, Yappy y otros métodos de pago, Shopify o WooCommerce y carritos abandonados.',
    h1: 'Guías de tiendas online y pagos en Panamá',
    breadcrumb: 'Tiendas online y pagos',
    lead: ['Desde crear la tienda hasta cobrar y recuperar ventas: las guías sobre e-commerce y medios de pago que se usan en Panamá.'],
    blocks: [
      {
        type: 'cards',
        h2: 'Empieza aquí',
        intro: 'Las páginas principales del tema.',
        items: [
          { h3: 'Tiendas Online en Panamá | E-commerce con Yappy y Pasarelas', text: 'Desarrollo de tiendas online en Panamá: catálogo, carrito, Yappy, pasarelas de pago locales y envíos. E-commerce que sí vende.', link: { slug: 'servicios/tiendas-online-ecommerce-panama', label: 'Ver la página' } },
          { h3: 'Integrar Yappy en tu Página Web | Pasarelas de Pago Panamá', text: 'Integramos el Botón de Pago Yappy y pasarelas con tarjeta en tu página web o tienda online. Cobra en línea como pagan los panameños.', link: { slug: 'funcionalidades/integracion-yappy-pasarelas-pago-panama', label: 'Ver la página' } },
        ],
      },
      {
        type: 'cards',
        h2: 'Guías del tema',
        items: [
          { h3: 'Cómo crear una tienda online en Panamá: guía completa 2026', text: 'Guía paso a paso para crear tu tienda online en Panamá: plataforma, catálogo, pagos con Yappy, envíos y logística local.', link: { slug: 'blog/como-crear-una-tienda-online-en-panama', label: 'Leer la guía' } },
          { h3: 'Cuánto cuesta una tienda online en Panamá', text: 'Una tienda online con Elemento Web parte desde $1,500 sin ITBMS. Qué define el precio final, qué se paga aparte y cuándo una tienda no te conviene.', link: { slug: 'blog/cuanto-cuesta-tienda-online-panama', label: 'Leer la guía' } },
          { h3: 'Shopify vs WooCommerce en Panamá: cuál te conviene', text: 'Comparativa honesta entre Shopify y WooCommerce para vender en Panamá: costos reales, comisiones, control, mantenimiento y cuál conviene según tu negocio.', link: { slug: 'blog/shopify-vs-woocommerce-panama', label: 'Leer la guía' } },
          { h3: 'Cómo integrar Yappy en tu tienda online paso a paso', text: 'Aprende a integrar el Botón de Pago Yappy en tu tienda online en Panamá: requisitos, pasos, comisiones y ventajas para cobrar sin fricción y vender más.', link: { slug: 'blog/como-integrar-yappy-tu-tienda-online', label: 'Leer la guía' } },
          { h3: 'Métodos de pago online en Panamá: Yappy, tarjetas y más', text: 'Panorama de los métodos de pago online en Panamá: Yappy, pasarelas con tarjeta y transferencias. Pros, contras y cuál elegir para vender más en tu tienda.', link: { slug: 'blog/metodos-de-pago-online-en-panama', label: 'Leer la guía' } },
          { h3: 'Cómo aumentar las ventas de tu tienda online en Panamá', text: 'Nueve tácticas para vender más en tu tienda online en Panamá: velocidad, Yappy, WhatsApp y recuperación de carritos.', link: { slug: 'blog/como-aumentar-ventas-tienda-online-panama', label: 'Leer la guía' } },
          { h3: 'Carritos abandonados: cómo recuperar esas ventas', text: 'Por qué se abandonan los carritos en Panamá y cómo recuperar esas ventas: recordatorios, checkout simple y pagos locales.', link: { slug: 'blog/carritos-abandonados-como-recuperar-ventas', label: 'Leer la guía' } },
        ],
      },
      { type: 'related', items: [{ slug: 'guias', label: 'Todas las guías' }, { slug: 'precios', label: 'Precios' }, { slug: 'casos-de-exito', label: 'Casos de éxito' }, { slug: 'contacto', label: 'Contacto' }] },
      { type: 'form', h2: '¿Quieres que lo veamos contigo?', intro: 'Cuéntanos tu caso y te respondemos el mismo día hábil.' },
    ],
  },
  {
    slug: 'guias/seo-y-posicionamiento',
    parent,
    title: 'Guías de SEO y posicionamiento web en Panamá',
    description: 'Guías de SEO para negocios en Panamá: cómo aparecer en Google, elegir palabras clave, SEO local, Google Business Profile, velocidad y cómo medir resultados.',
    h1: 'Guías de SEO y posicionamiento web en Panamá',
    breadcrumb: 'SEO y posicionamiento',
    lead: ['Lo que se puede y no se puede prometer en SEO, y cómo trabajarlo con método: palabras clave, SEO local, velocidad y medición.'],
    blocks: [
      {
        type: 'cards',
        h2: 'Empieza aquí',
        intro: 'Las páginas principales del tema.',
        items: [
          { h3: 'SEO y Posicionamiento Web en Panamá | Tráfico que Compra', text: 'Posicionamiento SEO en Panamá: contenido, técnica y autoridad para aparecer en Google donde busca tu cliente. Sin promesas mágicas.', link: { slug: 'crecimiento/seo-posicionamiento-web-panama', label: 'Ver la página' } },
          { h3: 'SEO Local y Google Maps en Panamá | Aparece Donde te Buscan', text: 'SEO local en Panamá: optimizamos tu ficha de Google, reseñas y presencia en Maps para que te encuentren cuando buscan tu servicio cerca.', link: { slug: 'crecimiento/seo-local-google-maps-panama', label: 'Ver la página' } },
        ],
      },
      {
        type: 'cards',
        h2: 'Guías del tema',
        items: [
          { h3: 'Cómo aparecer primero en Google en Panamá: guía real de SEO', text: 'Guía honesta para aparecer primero en Google en Panamá: cómo funciona el ranking, qué contenido y autoridad necesitas y en cuánto tiempo esperar resultados.', link: { slug: 'blog/como-aparecer-primero-en-google-en-panama', label: 'Leer la guía' } },
          { h3: 'SEO para pymes en Panamá: guía práctica para empezar', text: 'Guía de SEO para pymes en Panamá: pasos accionables con poco presupuesto, palabras clave locales, contenido útil y tu ficha de Google. Empieza hoy.', link: { slug: 'blog/seo-para-pymes-en-panama-guia', label: 'Leer la guía' } },
          { h3: 'Cómo elegir las palabras clave que sí traen clientes en Panamá', text: 'Cómo elegir palabras clave de SEO en Panamá: intención de búsqueda, términos locales y de cola larga, y cómo asignarlas.', link: { slug: 'blog/como-elegir-palabras-clave-seo-panama', label: 'Leer la guía' } },
          { h3: '¿Por qué mi página no aparece en Google? 8 razones', text: 'Tu web no aparece en Google y no sabes por qué. Estas son las 8 causas más comunes, desde problemas de indexación hasta falta de SEO, y cómo resolver cada una.', link: { slug: 'blog/por-que-mi-pagina-no-aparece-en-google', label: 'Leer la guía' } },
          { h3: 'Qué es el SEO local y cómo dominar Google Maps en Panamá', text: 'Qué es el SEO local y cómo aparecer en el mapa cuando alguien busca "cerca de mí" en Panamá. Guía práctica paso a paso.', link: { slug: 'blog/que-es-el-seo-local-y-google-maps-panama', label: 'Leer la guía' } },
          { h3: 'Google Business Profile: optimiza tu ficha en Panamá', text: 'Cómo optimizar tu ficha de Google Business Profile en Panamá para aparecer en Maps, ganar reseñas y atraer clientes de tu zona.', link: { slug: 'blog/optimizar-google-business-profile-panama', label: 'Leer la guía' } },
          { h3: 'Cómo mejorar la velocidad de carga de tu página web', text: 'Por qué la velocidad de tu web afecta el SEO y las ventas, cuáles son las causas más comunes de lentitud y qué hacer para mejorar tus Core Web Vitals.', link: { slug: 'blog/como-mejorar-la-velocidad-de-tu-pagina-web', label: 'Leer la guía' } },
          { h3: 'Cómo medir los resultados de tu página web: qué importa', text: 'Deja las métricas de vanidad. Aprende a medir lo que de verdad importa en tu web: visitas útiles, origen del tráfico, conversiones y clics a WhatsApp en Panamá.', link: { slug: 'blog/como-medir-los-resultados-de-tu-pagina-web', label: 'Leer la guía' } },
          { h3: 'Medir leads de WhatsApp con GA4 y CRM: guía práctica', text: 'Cómo medir consultas de WhatsApp y formulario: qué eventos registrar en GA4, qué guardar en el CRM y por qué un clic no es una venta.', link: { slug: 'blog/medir-leads-whatsapp-ga4-crm', label: 'Leer la guía' } },
          { h3: 'Checklist de migración SEO para rediseñar tu web', text: 'Lista práctica para rediseñar o migrar una web sin perder posicionamiento: qué hacer antes, durante y después, con redirecciones 301 y monitoreo.', link: { slug: 'recursos/checklist-migracion-seo', label: 'Leer la guía' } },
        ],
      },
      { type: 'related', items: [{ slug: 'guias', label: 'Todas las guías' }, { slug: 'precios', label: 'Precios' }, { slug: 'casos-de-exito', label: 'Casos de éxito' }, { slug: 'contacto', label: 'Contacto' }] },
      { type: 'form', h2: '¿Quieres que lo veamos contigo?', intro: 'Cuéntanos tu caso y te respondemos el mismo día hábil.' },
    ],
  },
  {
    slug: 'guias/whatsapp-ia-y-automatizacion',
    parent,
    title: 'Guías de WhatsApp, IA y automatización para tu negocio',
    description: 'Guías para vender por WhatsApp, usar IA y automatizar el seguimiento de clientes en Panamá: chatbots, CRM, n8n, campañas y embudos de venta.',
    h1: 'Guías de WhatsApp, IA y automatización para negocios',
    breadcrumb: 'WhatsApp, IA y automatización',
    lead: ['Cómo atender más rápido, no perder consultas y ordenar las ventas con WhatsApp, inteligencia artificial y automatizaciones.'],
    blocks: [
      {
        type: 'cards',
        h2: 'Empieza aquí',
        intro: 'Las páginas principales del tema.',
        items: [
          { h3: 'Inteligencia Artificial para Empresas en Panamá', text: 'Ecosistema de IA privado para tu empresa en Panamá: base de conocimiento (RAG) y automatización de procesos 24/7, siempre con control humano.', link: { slug: 'inteligencia-artificial-para-empresas-panama', label: 'Ver la página' } },
          { h3: 'Chatbot con IA para tu Página Web | WazaCRM Panamá', text: 'Chatbot con inteligencia artificial para tu web: responde con tu información real, capta datos y deriva a WhatsApp. Con WazaCRM, nuestro producto.', link: { slug: 'funcionalidades/chatbots-ia-web-wazacrm-panama', label: 'Ver la página' } },
        ],
      },
      {
        type: 'cards',
        h2: 'Guías del tema',
        items: [
          { h3: 'Cómo vender por WhatsApp en Panamá y no perder ventas', text: 'Aprende a vender por WhatsApp en Panamá sin perder ventas: WhatsApp Business, catálogo, respuestas rápidas, conectar tu web y automatizar con un chatbot de IA.', link: { slug: 'blog/como-vender-por-whatsapp-en-panama', label: 'Leer la guía' } },
          { h3: 'Chatbots con IA para negocios en Panamá', text: 'Qué es un chatbot con IA, en qué se diferencia del bot de botones, casos reales en Panamá y cómo integrarlo con tu web y tu WhatsApp sin complicarte.', link: { slug: 'blog/chatbots-con-ia-para-negocios-en-panama', label: 'Leer la guía' } },
          { h3: 'Cómo atender a tus clientes 24/7 con un asistente de IA', text: 'El costo real de no responder a tiempo y cómo un asistente de IA capta clientes fuera de horario sin inventar respuestas.', link: { slug: 'blog/como-atender-clientes-24-7-con-un-asistente-de-ia', label: 'Leer la guía' } },
          { h3: 'Inteligencia artificial para pequeñas empresas en Panamá', text: 'Usos prácticos y accesibles de la IA para pymes panameñas: atención, contenido y automatización. Por dónde empezar sin gastar de más y qué mitos ignorar.', link: { slug: 'blog/inteligencia-artificial-para-pequenas-empresas-en-panama', label: 'Leer la guía' } },
          { h3: 'Automatizaciones con n8n para pymes: ahorra horas cada semana', text: 'Qué es n8n y cómo automatizar tareas repetitivas sin programar: del formulario al CRM y a WhatsApp, sin copiar datos a mano.', link: { slug: 'blog/automatizaciones-con-n8n-para-pymes', label: 'Leer la guía' } },
          { h3: 'Cómo automatizar el seguimiento de clientes en Panamá', text: 'Cómo automatizar el seguimiento de clientes en Panamá con WhatsApp, CRM y flujos automáticos. Deja de perder ventas por olvido.', link: { slug: 'blog/automatizar-seguimiento-clientes-panama', label: 'Leer la guía' } },
          { h3: 'CRM con WhatsApp: cómo vender más y no perder clientes', text: 'Por qué vender por WhatsApp necesita un CRM, cómo armar un embudo de ventas, dar seguimiento y dejar de perder conversaciones entre cientos de chats sin orden.', link: { slug: 'blog/crm-con-whatsapp-para-vender-mas-en-panama', label: 'Leer la guía' } },
          { h3: 'Cómo hacer campañas de WhatsApp masivo en Panamá', text: 'Guía para campañas de WhatsApp masivo en Panamá con la API oficial: plantillas aprobadas, opt-in, cómo evitar bloqueos y casos donde de verdad funciona.', link: { slug: 'blog/como-hacer-campanas-de-whatsapp-masivo-en-panama', label: 'Leer la guía' } },
          { h3: 'Embudo de ventas: de visita a cliente, paso a paso', text: 'Qué es un embudo de ventas y cómo construir uno en Panamá: de la atracción al cierre, con web, WhatsApp y automatización.', link: { slug: 'blog/embudo-de-ventas-para-negocios-panama', label: 'Leer la guía' } },
        ],
      },
      { type: 'related', items: [{ slug: 'guias', label: 'Todas las guías' }, { slug: 'precios', label: 'Precios' }, { slug: 'casos-de-exito', label: 'Casos de éxito' }, { slug: 'contacto', label: 'Contacto' }] },
      { type: 'form', h2: '¿Quieres que lo veamos contigo?', intro: 'Cuéntanos tu caso y te respondemos el mismo día hábil.' },
    ],
  },
  {
    slug: 'guias/marketing-y-pauta',
    parent,
    title: 'Guías de marketing digital y pauta en Panamá',
    description: 'Guías de marketing digital para negocios en Panamá: Google Ads o Facebook Ads, cuánto invertir en pauta, email marketing y contenido para redes.',
    h1: 'Guías de marketing digital y pauta en Panamá',
    breadcrumb: 'Marketing y pauta',
    lead: ['Decisiones de pauta y marketing explicadas sin promesas: dónde conviene invertir, cuánto y cómo medirlo.'],
    blocks: [
      {
        type: 'cards',
        h2: 'Empieza aquí',
        intro: 'Las páginas principales del tema.',
        items: [
          { h3: 'Marketing Digital y Pauta en Panamá | Google, Meta y Más', text: 'Marketing digital en Panamá: Google Ads, Facebook e Instagram Ads, contenido para redes, email marketing y automatizaciones. Fee claro, tu inversión aparte.', link: { slug: 'marketing', label: 'Ver la página' } },
          { h3: 'Agencia de Google Ads en Panamá | Gestión de Campañas', text: 'Gestión de Google Ads en Panamá: búsqueda, display y remarketing. Aparece cuando tu cliente busca. Fee de gestión claro, tu inversión va directo a Google.', link: { slug: 'marketing/google-ads-panama', label: 'Ver la página' } },
        ],
      },
      {
        type: 'cards',
        h2: 'Guías del tema',
        items: [
          { h3: 'Google Ads vs Facebook Ads: cuál conviene en Panamá', text: 'Google Ads vs Facebook Ads en Panamá: intención de compra vs descubrimiento, cuándo usar cada uno, cómo repartir el presupuesto y por qué conviene combinarlos.', link: { slug: 'blog/google-ads-vs-facebook-ads-en-panama', label: 'Leer la guía' } },
          { h3: '¿Cuánto invertir en publicidad digital en Panamá?', text: 'Cómo definir tu presupuesto de publicidad digital en Panamá: costo por lead, fase de prueba y cuánto arriesgar al inicio.', link: { slug: 'blog/cuanto-invertir-en-publicidad-digital-en-panama', label: 'Leer la guía' } },
          { h3: 'Email marketing para negocios en Panamá: guía 2026', text: 'Guía de email marketing para negocios en Panamá: construir una lista propia, automatizaciones de bienvenida, carrito y reactivación, y cuidar la entregabilidad.', link: { slug: 'blog/email-marketing-para-negocios-en-panama', label: 'Leer la guía' } },
          { h3: 'Marketing de contenidos para redes sociales en Panamá', text: 'Cómo hacer marketing de contenidos para redes en Panamá: estrategia por pilares, Reels, constancia real y cómo llevar el contenido de las redes hacia tu web.', link: { slug: 'blog/marketing-de-contenidos-para-redes-sociales-panama', label: 'Leer la guía' } },
        ],
      },
      { type: 'related', items: [{ slug: 'guias', label: 'Todas las guías' }, { slug: 'precios', label: 'Precios' }, { slug: 'casos-de-exito', label: 'Casos de éxito' }, { slug: 'contacto', label: 'Contacto' }] },
      { type: 'form', h2: '¿Quieres que lo veamos contigo?', intro: 'Cuéntanos tu caso y te respondemos el mismo día hábil.' },
    ],
  },
  {
    slug: 'guias/diseno-web-miami',
    parent,
    title: 'Guías de diseño web para negocios hispanos de Miami',
    description: 'Guías para negocios hispanos de Miami que quieren una web: cuánto cuesta, cómo elegir agencia y qué necesita el sitio. Servicio remoto desde Panamá.',
    h1: 'Guías de diseño web para negocios de Miami',
    breadcrumb: 'Diseño web para Miami',
    lead: ['Para negocios de Miami-Dade que operan en español: costo, cómo elegir agencia y qué debe tener la web. Trabajamos remoto desde Panamá, en dólares.'],
    blocks: [
      {
        type: 'cards',
        h2: 'Empieza aquí',
        intro: 'Las páginas principales del tema.',
        items: [
          { h3: 'Diseño Web en Miami en Español', text: 'Agencia de diseño web para negocios hispanos de Miami-Dade. Mismo huso horario, mismo precio en USD, soporte 100% en español. Sede en Panamá, servicio remoto.', link: { slug: 'miami', label: 'Ver la página' } },
          { h3: 'Diseño Web en Miami en Español | Sin Sobreprecio de Agencia de EE.UU.', text: 'Diseño web para negocios hispanos de Miami: mismo huso horario, mismo precio en USD, soporte 100% en español. Sede en Panamá, servicio remoto, sin intermediarios.', link: { slug: 'miami/diseno-web-en-miami-en-espanol', label: 'Ver la página' } },
          { h3: 'Diseño Web en Doral, Miami | Empresas y Comercio Internacional', text: 'Diseño web para empresas de Doral: importadoras, bienes raíces, clínicas y servicios profesionales. Sede en Panamá, servicio remoto, precios en USD.', link: { slug: 'miami/diseno-web-doral', label: 'Ver la página' } },
          { h3: 'Diseño Web en Hialeah, Miami | Negocios y Comercio Local', text: 'Diseño web para negocios de Hialeah: retail, servicios y comercio de barrio. Sede en Panamá, servicio remoto, en español, precios en USD.', link: { slug: 'miami/diseno-web-hialeah', label: 'Ver la página' } },
        ],
      },
      {
        type: 'cards',
        h2: 'Guías del tema',
        items: [
          { h3: 'Cuánto cuesta una página web para un negocio en Miami', text: 'Cómo calcular el costo de una web para tu negocio en Miami con una agencia remota en Panamá: qué sumar, precios propios en USD e impuestos.', link: { slug: 'blog/cuanto-cuesta-pagina-web-miami', label: 'Leer la guía' } },
          { h3: 'Agencia de diseño web en Miami en español: cómo elegir', text: 'Criterios y preguntas para elegir agencia de diseño web en Miami si tu negocio opera en español: proceso, dominio, mantenimiento, medición y pagos.', link: { slug: 'blog/agencia-diseno-web-miami-en-espanol', label: 'Leer la guía' } },
          { h3: 'Diseño web para negocios hispanos en Miami: guía', text: 'Qué debe tener la web de un negocio hispano de Miami-Dade: español nativo, WhatsApp, precio visible, SEO local, versión bilingüe y velocidad en celular.', link: { slug: 'blog/diseno-web-para-negocios-hispanos-miami', label: 'Leer la guía' } },
        ],
      },
      { type: 'related', items: [{ slug: 'guias', label: 'Todas las guías' }, { slug: 'precios', label: 'Precios' }, { slug: 'casos-de-exito', label: 'Casos de éxito' }, { slug: 'contacto', label: 'Contacto' }] },
      { type: 'form', h2: '¿Quieres que lo veamos contigo?', intro: 'Cuéntanos tu caso y te respondemos el mismo día hábil.' },
    ],
  },
  {
    slug: 'guias/diseno-web-por-industria',
    parent,
    title: 'Guías de diseño web por industria en Panamá',
    description: 'Guías de diseño web para abogados, clínicas, restaurantes, hoteles, constructoras, contadores y más sectores en Panamá: qué necesita la web de cada uno.',
    h1: 'Guías de diseño web por industria en Panamá',
    breadcrumb: 'Diseño web por industria',
    lead: ['Cada sector vende distinto. Elige el tuyo para ver qué debe tener su web, y consulta la página de la industria para ver el servicio.'],
    blocks: [
      {
        type: 'cards',
        h2: 'Empieza aquí',
        intro: 'Las páginas principales del tema.',
        items: [
          { h3: 'Diseño Web por Industria en Panamá | 30 Nichos Cubiertos', text: 'Diseño web por industria en Panamá: abogados, contadores, bienes raíces, restaurantes, turismo, clínicas, constructoras, retail y 22 nichos más.', link: { slug: 'industrias', label: 'Ver la página' } },
        ],
      },
      {
        type: 'cards',
        h2: 'Guías del tema',
        items: [
          { h3: 'Diseño web para abogados en Panamá: qué genera consultas', text: 'Qué debe tener la web de un abogado en Panamá: credibilidad sin prometer resultados, un formulario que filtra el caso y SEO por área de práctica.', link: { slug: 'blog/diseno-web-para-abogados-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para agencias de aduana en Panamá: qué capta', text: 'Diseño web para agencias de aduana y Zona Libre en Panamá: cotización clara para el importador primerizo, seguimiento de expediente y cuándo no conviene.', link: { slug: 'blog/diseno-web-para-agencias-aduaneras-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para agencias de viajes en Panamá: qué reserva', text: 'Qué debe tener la web de una agencia de viajes en Panamá: reserva con depósito, fotos que venden la experiencia e itinerarios claros.', link: { slug: 'blog/diseno-web-para-agencias-de-viajes-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para aire acondicionado en Panamá: dos negocios', text: 'Una empresa de A/C en Panamá vende dos cosas: la reparación de hoy y el contrato anual. Cómo separar las dos rutas en la web sin perder ninguna.', link: { slug: 'blog/diseno-web-para-aire-acondicionado-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para arquitectos en Panamá: el portafolio vende', text: 'Qué debe tener el portafolio de un arquitecto en Panamá: fotos reales de proyectos, una página por obra con su historia y cuándo no conviene todavía.', link: { slug: 'blog/diseno-web-para-arquitectos-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para belleza y spas en Panamá: llena la agenda', text: 'Qué debe tener la web de un salón o spa en Panamá: reserva por estilista, portafolio real de resultados y recordatorios contra el ausentismo.', link: { slug: 'blog/diseno-web-para-belleza-spa-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para bienes raíces: lo que de verdad convierte', text: 'Qué debe tener la web de una inmobiliaria en Panamá para vender: catálogo con filtros, formulario por propiedad, WhatsApp y cuándo no conviene tenerla.', link: { slug: 'blog/diseno-web-para-bienes-raices-panama', label: 'Leer la guía' } },
          { h3: 'Web para clínicas estéticas en Panamá: qué convierte', text: 'Qué debe tener la web de una clínica estética en Panamá: antes y después con consentimiento, reservas online, precios orientativos y un WhatsApp discreto.', link: { slug: 'blog/diseno-web-para-clinicas-esteticas-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para clínicas y centros de salud en Panamá', text: 'Qué debe tener la web de una clínica en Panamá: citas online, especialidades claras, confianza real y cuándo no conviene invertir aún.', link: { slug: 'blog/diseno-web-para-clinicas-salud-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para concesionarios en Panamá: qué vende el auto', text: 'Qué debe tener la web de un concesionario en Panamá: fotos reales de cada unidad, filtros por marca y precio, y financiamiento como llamado principal.', link: { slug: 'blog/diseno-web-para-concesionarios-autos-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para constructoras en Panamá: qué convence', text: 'Qué debe tener la web de una constructora en Panamá: portafolio con avance de obra, certificaciones a la vista y una cotización honesta.', link: { slug: 'blog/diseno-web-para-constructoras-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para consultoras en Panamá: qué convierte', text: 'Qué necesita la web de una consultora en Panamá: casos reales con permiso del cliente, un formulario que filtra por presupuesto y blog propio.', link: { slug: 'blog/diseno-web-para-consultoras-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para contadores en Panamá: qué no puede faltar', text: 'Qué debe tener la web de un contador en Panamá: credenciales visibles, servicios separados y por qué posicionar antes de la temporada de renta.', link: { slug: 'blog/diseno-web-para-contadores-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para cooperativas en Panamá: qué revisa un socio', text: 'Qué necesita la web de una cooperativa en Panamá: simulador de cuota, tasas publicadas y la transparencia que un socio-dueño espera.', link: { slug: 'blog/diseno-web-para-cooperativas-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para dentistas en Panamá: qué debe incluir', text: 'Diseño web para dentistas en Panamá: citas online, una página por especialidad, fotos que no espantan, seguros visibles y cuándo NO conviene hacer marketing.', link: { slug: 'blog/diseno-web-para-dentistas-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para colegios en Panamá: qué decide matricular', text: 'Qué debe tener la web de un colegio en Panamá: admisiones sin fricción, portal de padres honesto y fotos reales del campus, no de stock.', link: { slug: 'blog/diseno-web-para-educacion-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para eventos y catering en Panamá: qué vende', text: 'Qué debe tener la web de un catering o salón de eventos en Panamá: portafolio real, paquetes por tipo de evento y disponibilidad de fecha visible.', link: { slug: 'blog/diseno-web-para-eventos-catering-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para ferreterías en Panamá: vender más', text: 'Qué necesita la web de una ferretería en Panamá: catálogo con disponibilidad real, cotización rápida para contratistas y cuándo NO conviene.', link: { slug: 'blog/diseno-web-para-ferreterias-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para gimnasios en Panamá: qué vende membresías', text: 'Qué necesita la web de un gimnasio en Panamá: inscripción y reserva de clases sin fricción, fotos reales y precios de membresía claros.', link: { slug: 'blog/diseno-web-para-gimnasios-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para importadoras en Panamá: catálogo que vende', text: 'Qué necesita la web de una importadora en Panamá: catálogo por línea de producto, alcance regional y cuándo no conviene invertir.', link: { slug: 'blog/diseno-web-para-importadoras-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para imprentas en Panamá: la cotización completa', text: 'Qué necesita la web de una imprenta en Panamá: formulario de cotización completo, especificaciones de arte y una página por línea de producción.', link: { slug: 'blog/diseno-web-para-imprentas-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para logística en Panamá: qué convence a un B2B', text: 'Qué debe tener la web de una empresa de logística en Panamá: credenciales verificables, cotizador de envío y cobertura de rutas clara, no adjetivos.', link: { slug: 'blog/diseno-web-para-logistica-transporte-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para navieras en Panamá: qué decide el contrato', text: 'Qué debe tener la web de una naviera o proveedor marítimo en Panamá: credenciales verificables, versión en inglés y contenido técnico, no genérico.', link: { slug: 'blog/diseno-web-para-navieras-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para negocios hispanos en Miami: guía', text: 'Qué debe tener la web de un negocio hispano de Miami-Dade: español nativo, WhatsApp, precio visible, SEO local, versión bilingüe y velocidad en celular.', link: { slug: 'blog/diseno-web-para-negocios-hispanos-miami', label: 'Leer la guía' } },
          { h3: 'Diseño web para restaurantes en Panamá: qué debe tener', text: 'Qué debe tener la web de un restaurante en Panamá: menú con fotos reales, SEO local, reservas o pedidos, y cuándo todavía no conviene.', link: { slug: 'blog/diseno-web-para-restaurantes-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para retail y moda en Panamá: más que Instagram', text: 'Qué debe tener una tienda de moda o retail en Panamá: catálogo con filtros, checkout propio e integración con Instagram Shopping.', link: { slug: 'blog/diseno-web-para-retail-moda-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para seguridad y vigilancia en Panamá: dos rutas', text: 'Qué debe tener la web de una empresa de seguridad en Panamá: credenciales para el comité que decide y una sección de empleo que el rubro no usa.', link: { slug: 'blog/diseno-web-para-seguridad-vigilancia-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para corredores de seguros en Panamá: qué cotiza', text: 'Qué necesita la web de un corredor de seguros en Panamá: una página por ramo, un cotizador simple y por qué el SEO en este rubro toma tiempo real.', link: { slug: 'blog/diseno-web-para-seguros-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para talleres automotrices en Panamá', text: 'Qué debe tener la web de un taller mecánico en Panamá: precios de referencia, citas online y reseñas, para bajar la desconfianza del rubro.', link: { slug: 'blog/diseno-web-para-talleres-automotrices-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para hoteles y turismo en Panamá: reserva directa', text: 'Qué debe tener la web de un hotel en Panamá para ganar reservas directas sin pagar comisión: fotos reales, motor de reservas y contenido de destino.', link: { slug: 'blog/diseno-web-para-turismo-hoteles-panama', label: 'Leer la guía' } },
          { h3: 'Diseño web para veterinarias en Panamá: citas y confianza', text: 'Qué necesita la web de una veterinaria en Panamá: cita en línea central, servicios claros y fotos que calman en vez de asustar.', link: { slug: 'blog/diseno-web-para-veterinarias-panama', label: 'Leer la guía' } },
          { h3: 'Reservas directas para tours: cómo recibirlas en tu web', text: 'Cómo un negocio de tours puede recibir reservas directas: selector de tour, depósito, varios idiomas, WhatsApp para dudas y políticas claras.', link: { slug: 'blog/reservas-directas-tours-san-blas', label: 'Leer la guía' } },
        ],
      },
      { type: 'related', items: [{ slug: 'guias', label: 'Todas las guías' }, { slug: 'precios', label: 'Precios' }, { slug: 'casos-de-exito', label: 'Casos de éxito' }, { slug: 'contacto', label: 'Contacto' }] },
      { type: 'form', h2: '¿Quieres que lo veamos contigo?', intro: 'Cuéntanos tu caso y te respondemos el mismo día hábil.' },
    ],
  },
];
